name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make integration_test.sh executable
        run: chmod +x ./integration_test.sh  # Make the script executable

      - name: Run integration test
        run: ./integration_test.sh  # Execute the integration test script
