name: CI

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Integration Tests
      run: ./integration_test.sh
